# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'siciDemo' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for siciDemo
  pod 'Alamofire'
  pod 'SnapKit' #AutoLayout
  pod 'SwiftyJSON' #JSON解析

  target 'siciDemoTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'siciDemoUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
